### ISSUE TITLE
add option to choose which text editor to use.

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#37]
1: add option to choose which text editor to use when selecting the "editor" extension, similar to what happens when using the "everything" extension where you have to select the .exe in the program directory. because I use notepad++ and not the standard windows text editor. OR
2: snipdo can detect which text editors (notepad++, windows notepad, etc) are present in windows for the user to choose which one to use as the default editor.

**Comment by poochie89** [comment]
1. Since every app uses different cmd line arguments or doesnt support cmd line at all it can not be done this way
2. Best way is to simply assign your text editor to .txt (or antoher extension), and do it the way the editor extension does it (creates a tmp file with that extension, writes the snipdo text to it and opens it)

**Comment by cleuton4k** [comment]
could you create an extension for notepad++ and make it available in the extension store?

**Comment by poochie89** [comment]
Its available now
